#!/usr/bin/env python3
"""Render the single canonical household prompt. No writes to live workspaces."""
import argparse
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
def render(mode="combined"):
    prompts = Path(__file__).resolve().parent / "prompts"
    grocery = (ROOT / "tools/grocery-list/skill/SKILL.md").read_text()
    if grocery.startswith("---"):
        grocery = grocery.split("---", 2)[2].lstrip()
    if mode == "base":
        return (prompts / "BASE.md").read_text()
    if mode == "groceries":
        return grocery
    if mode == "doctor":
        return (prompts / "DOCTOR.md").read_text()
    base = (prompts / "BASE.md").read_text()
    start = base.index("<!-- MODE_ROUTING_START -->")
    end = base.index("<!-- MODE_ROUTING_END -->", start) + len("<!-- MODE_ROUTING_END -->")
    base = base[:start] + (
        "Explicit mode routing is not enabled in this configuration. Handle Grocery "
        "and Doctor requests by their stated intent. Short followups belong to the "
        "current task; ask briefly when the intended task is ambiguous. Do not offer "
        "mode-switch commands. Changing tasks does not approve pending actions."
    ) + base[end:]
    return "<!-- Generated by tools/household-config/render.py. Edit source prompts and Grocery SKILL.md. -->\n\n" + "\n\n".join([base.strip(), grocery.strip(), (prompts / "DOCTOR.md").read_text().strip()]) + "\n"
if __name__ == "__main__":
    p = argparse.ArgumentParser(); p.add_argument("--output", type=Path); p.add_argument("--mode", choices=["combined", "base", "groceries", "doctor"], default="combined"); args=p.parse_args()
    text=render(args.mode)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True); args.output.write_text(text)
    else:
        print(text, end="")
